# Generated by Django 2.1.3 on 2018-11-22 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0002_auto_20181122_1103'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('acknowledge', 'acknowledge'), ('unacknowledge', 'unacknowledge'), ('resolve', 'resolve'), ('silence_service', 'silence service'), ('unsilence_service', 'unsilence service'), ('silence_incident', 'silence incident'), ('unsilence_incident', 'unsilence incident'), ('forward', 'forward'), ('log', 'log'), ('notified', 'notified'), ('notification_failed', 'notification failed'), ('trigger', 'trigger')], default='log', max_length=100)),
                ('data', models.TextField()),
                ('occurred_at', models.DateTimeField()),
                ('incident_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='incidents.Incident')),
                ('service_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Service')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'eventlog',
                'verbose_name_plural': 'eventlog',
            },
        ),
    ]
