# Generated by Django 2.1.3 on 2018-11-22 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifier', models.CharField(max_length=30)),
                ('message', models.CharField(max_length=500)),
                ('send_at', models.DateTimeField()),
                ('incident', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='incidents.Incident')),
                ('user_to_notify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'scheduled_notifications',
                'verbose_name_plural': 'scheduled_notifications',
                'db_table': 'openduty_schedulednotification',
            },
        ),
        migrations.CreateModel(
            name='UserNotificationMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('method', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user_notification_method',
                'verbose_name_plural': 'user_notification_methods',
                'db_table': 'openduty_usernotificationmethod',
            },
        ),
    ]
