# Generated by Django 2.1.3 on 2018-11-22 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0011_event_calendar_not_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulePolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('repeat_times', models.IntegerField()),
            ],
            options={
                'verbose_name': 'schedule_policy',
                'verbose_name_plural': 'schedule_policies',
            },
        ),
        migrations.CreateModel(
            name='SchedulePolicyRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('escalate_after', models.IntegerField()),
                ('group_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.Calendar')),
                ('schedule_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='schedules.SchedulePolicy')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'schedule_policy_rule',
                'verbose_name_plural': 'schedule_policy_rules',
            },
        ),
    ]
