# Generated by Django 2.1.3 on 2018-11-29 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20181129_1535'),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulepolicyrule',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='schedulepolicyrule',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='schedulepolicyrule',
            name='schedule_policy',
        ),
        migrations.RemoveField(
            model_name='schedulepolicyrule',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='SchedulePolicy',
        ),
        migrations.DeleteModel(
            name='SchedulePolicyRule',
        ),
    ]
